import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Goa Police HelpDesk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script src="./node_modules/preline/dist/preline.js"></script>
        <script src="https://cdn.botpress.cloud/webchat/v2.1/inject.js"></script>
          <script src="https://mediafiles.botpress.cloud/ba25eea6-3827-4b7c-86f5-702d509c82e0/webchat/v2.1/config.js"></script>
      </body>
    </html>
  );
}
